name: e_campus
description: "E-Campus - A Smart Digital Campus Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  firebase_messaging: ^16.4.3

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.5.3

  # UI & Design
  google_fonts: ^8.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  animate_do: ^5.1.0
  percent_indicator: ^4.2.5

  # Charts
  fl_chart: ^1.0.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # File Handling
  image_picker: ^1.1.2
  file_picker: ^11.0.2
  path_provider: ^2.1.5
  open_file: ^4.0.0

  # PDF
  syncfusion_flutter_pdfviewer: ^33.2.13

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

  # Icons
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/


